use ply_rs_bw::{PlyAccess, ToPly};

#[derive(Debug, Default, PlyAccess, Clone)]
struct Vertex {
    #[ply(name = "x")] x: f32,
    #[ply(name = "y")] y: f32,
    #[ply(name = "z")] z: f32,
}

#[derive(Debug, Default, PlyAccess, Clone)]
struct Face {
    #[ply(name = "vertex_indices")] indices: Vec<i32>,
}

#[derive(Debug, ToPly)]
struct Mesh {
    #[ply(name = "vertex")]
    vertices: Vec<Vertex>,
    #[ply(name = "face")]
    faces: Vec<Face>,
}

fn create_tetrahedron_mesh() -> Mesh {
    let vertices = vec![
        Vertex { x: 1.0, y: 1.0, z: 1.0 },
        Vertex { x: 1.0, y: -1.0, z: -1.0 },
        Vertex { x: -1.0, y: 1.0, z: -1.0 },
        Vertex { x: -1.0, y: -1.0, z: 1.0 },
    ];

    let faces = vec![
        Face { indices: vec![0, 1, 2] },
        Face { indices: vec![0, 3, 1] },
        Face { indices: vec![0, 2, 3] },
        Face { indices: vec![1, 3, 2] },
    ];

    Mesh { vertices, faces }
}

fn main() {
    let mesh = create_tetrahedron_mesh();
    let mut buf = Vec::<u8>::new();
    
    // Use the trait method generated by ToPly
    let written = mesh.write_ply(&mut buf).unwrap();
    println!("{} bytes written", written);

    let output = String::from_utf8(buf).unwrap();
    println!("Written PLY data:\n{}", output);
}
