name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master"]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Check documentation
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo doc --no-deps --all-features

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Build without features
        run: cargo build --no-default-features --verbose

      - name: Run tests without features
        run: cargo test --no-default-features --verbose

      - name: Build all examples
        run: cargo build --examples

      - name: Build all examples without features
        run: cargo build --examples --no-default-features
